overwrite: true
schema:
  - https://api.github.com/graphql:
      headers:
        User-Agent: velenyx
        Authorization: 'Bearer ${GITHUB_PERSONAL_TOKEN}'
documents: './app/_src/graphql/documents/*.gql'
